apiVersion: serving.kserve.io/v1alpha1
kind: ServingRuntime
metadata:
  name: guardrails-detector-runtime-guardian
  annotations:
    openshift.io/display-name: Guardrails Detector ServingRuntime for KServe
    opendatahub.io/recommended-accelerators: '["nvidia.com/gpu"]'
  labels:
    opendatahub.io/dashboard: 'true'
spec:
  annotations:
    prometheus.io/port: '8000'
    prometheus.io/path: '/metrics'
  multiModel: false
  supportedModelFormats:
    - autoSelect: true
      name: guardrails-detector-huggingface
  containers:
    - name: kserve-container
      image: quay.io/rh-ee-mmisiura/guardrails-detector-huggingface:3d51741
      command:
        - uvicorn
        - app:app
      args:
        - "--workers"
        - "1"
        - "--host"
        - "0.0.0.0"
        - "--port"
        - "8000"
        - "--log-config"
        - "/common/log_conf.yaml"
      env:
        - name: MODEL_DIR
          value: /mnt/models
        - name: HF_HOME
          value: /tmp/hf_home
        - name: DETECTOR_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
      ports:
        - containerPort: 8000
          protocol: TCP
      resources:
        requests:
          memory: "18Gi"  # pre-allocate 18Gi of memory -- might be needed for larger models
          cpu: "1"       # reserve 1 CPU core
        limits:
          memory: "20Gi"  # limit to 20Gi of memory
          cpu: "2"       # limit to 2 CPU cores